# Venture Funding with Deep Learning

You work as a risk management associate at Alphabet Soup, a venture capital firm. Alphabet Soup’s business team receives many funding applications from startups every day. This team has asked you to help them create a model that predicts whether applicants will be successful if funded by Alphabet Soup.

The business team has given you a CSV containing more than 34,000 organizations that have received funding from Alphabet Soup over the years. With your knowledge of machine learning and neural networks, you decide to use the features in the provided dataset to create a binary classifier model that will predict whether an applicant will become a successful business. The CSV file contains a variety of information about these businesses, including whether or not they ultimately became successful.

## Instructions:

The steps for this challenge are broken out into the following sections:

* Prepare the data for use on a neural network model.

* Compile and evaluate a binary classification model using a neural network.

* Optimize the neural network model.

### Prepare the Data for Use on a Neural Network Model 

Using your knowledge of Pandas and scikit-learn’s `StandardScaler()`, preprocess the dataset so that you can use it to compile and evaluate the neural network model later.

Open the starter code file, and complete the following data preparation steps:

1. Read the `applicants_data.csv` file into a Pandas DataFrame. Review the DataFrame, looking for categorical variables that will need to be encoded, as well as columns that could eventually define your features and target variables.   

2. Drop the “EIN” (Employer Identification Number) and “NAME” columns from the DataFrame, because they are not relevant to the binary classification model.
 
3. Encode the dataset’s categorical variables using `OneHotEncoder`, and then place the encoded variables into a new DataFrame.

4. Add the original DataFrame’s numerical variables to the DataFrame containing the encoded variables.

> **Note** To complete this step, you will employ the Pandas `concat()` function that was introduced earlier in this course. 

5. Using the preprocessed data, create the features (`X`) and target (`y`) datasets. The target dataset should be defined by the preprocessed DataFrame column “IS_SUCCESSFUL”. The remaining columns should define the features dataset. 

6. Split the features and target sets into training and testing datasets.

7. Use scikit-learn's `StandardScaler` to scale the features data.

### Compile and Evaluate a Binary Classification Model Using a Neural Network

Use your knowledge of TensorFlow to design a binary classification deep neural network model. This model should use the dataset’s features to predict whether an Alphabet Soup&ndash;funded startup will be successful based on the features in the dataset. Consider the number of inputs before determining the number of layers that your model will contain or the number of neurons on each layer. Then, compile and fit your model. Finally, evaluate your binary classification model to calculate the model’s loss and accuracy. 
 
To do so, complete the following steps:

1. Create a deep neural network by assigning the number of input features, the number of layers, and the number of neurons on each layer using Tensorflow’s Keras.

> **Hint** You can start with a two-layer deep neural network model that uses the `relu` activation function for both layers.

2. Compile and fit the model using the `binary_crossentropy` loss function, the `adam` optimizer, and the `accuracy` evaluation metric.

> **Hint** When fitting the model, start with a small number of epochs, such as 20, 50, or 100.

3. Evaluate the model using the test data to determine the model’s loss and accuracy.

4. Save and export your model to an HDF5 file, and name the file `AlphabetSoup.h5`. 

### Optimize the Neural Network Model

Using your knowledge of TensorFlow and Keras, optimize your model to improve the model's accuracy. Even if you do not successfully achieve a better accuracy, you'll need to demonstrate at least two attempts to optimize the model. You can include these attempts in your existing notebook. Or, you can make copies of the starter notebook in the same folder, rename them, and code each model optimization in a new notebook. 

> **Note** You will not lose points if your model does not achieve a high accuracy, as long as you make at least two attempts to optimize the model.

To do so, complete the following steps:

1. Define at least three new deep neural network models (the original plus 2 optimization attempts). With each, try to improve on your first model’s predictive accuracy.

> **Rewind** Recall that perfect accuracy has a value of 1, so accuracy improves as its value moves closer to 1. To optimize your model for a predictive accuracy as close to 1 as possible, you can use any or all of the following techniques:
>
> * Adjust the input data by dropping different features columns to ensure that no variables or outliers confuse the model.
>
> * Add more neurons (nodes) to a hidden layer.
>
> * Add more hidden layers.
>
> * Use different activation functions for the hidden layers.
>
> * Add to or reduce the number of epochs in the training regimen.

2. After finishing your models, display the accuracy scores achieved by each model, and compare the results.

3. Save each of your models as an HDF5 file.

In [1]:
# Imports
import pandas as pd
from pathlib import Path
import tensorflow as tf
from tensorflow.keras.layers import Dense
from tensorflow.keras.models import Sequential
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler,OneHotEncoder

---

## Prepare the data to be used on a neural network model

### Step 1: Read the `applicants_data.csv` file into a Pandas DataFrame. Review the DataFrame, looking for categorical variables that will need to be encoded, as well as columns that could eventually define your features and target variables.

In [11]:
# Read the applicants_data.csv file from the Resources folder into a Pandas DataFrame
applicant_data_df = Path('./Resources/applicants_data.csv')
applicant_data_df = pd.read_csv(applicant_data_df)

# Review the DataFrame
# YOUR CODE HERE
applicant_data_df

,EIN,NAME,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL
0,10520599,BLUE KNIGHTS MOTORCYCLE CLUB,T10,Independent,C1000,ProductDev,Association,1,0,N,5000,1
1,10531628,AMERICAN CHESAPEAKE CLUB CHARITABLE TR,T3,Independent,C2000,Preservation,Co-operative,1,1-9999,N,108590,1
2,10547893,ST CLOUD PROFESSIONAL FIREFIGHTERS,T5,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
3,10553066,SOUTHSIDE ATHLETIC ASSOCIATION,T3,CompanySponsored,C2000,Preservation,Trust,1,10000-24999,N,6692,1
4,10556103,GENETIC RESEARCH INSTITUTE OF THE DESERT,T3,Independent,C1000,Heathcare,Trust,1,100000-499999,N,142590,1
...,...,...,...,...,...,...,...,...,...,...,...,...
34294,996009318,THE LIONS CLUB OF HONOLULU KAMEHAMEHA,T4,Independent,C1000,ProductDev,Association,1,0,N,5000,0
34295,996010315,INTERNATIONAL ASSOCIATION OF LIONS CLUBS,T4,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
34296,996012607,PTA HAWAII CONGRESS,T3,CompanySponsored,C2000,Preservation,Association,1,0,N,5000,0
34297,996015768,AMERICAN FEDERATION OF GOVERNMENT EMPLOYEES LO...,T5,Independent,C3000,ProductDev,Association,1,0,N,5000,1
34298,996086871,WATERHOUSE CHARITABLE TR,T3,Independent,C1000,Preservation,Co-operative,1,1M-5M,N,36500179,0

In [12]:
# Review the data types associated with the columns
# YOUR CODE HERE
applicant_data_df.dtypes

EIN                        int64
NAME                      object
APPLICATION_TYPE          object
AFFILIATION               object
CLASSIFICATION            object
USE_CASE                  object
ORGANIZATION              object
STATUS                     int64
INCOME_AMT                object
SPECIAL_CONSIDERATIONS    object
ASK_AMT                    int64
IS_SUCCESSFUL              int64
dtype: object

### Step 2: Drop the “EIN” (Employer Identification Number) and “NAME” columns from the DataFrame, because they are not relevant to the binary classification model.

In [13]:
# Drop the 'EIN' and 'NAME' columns from the DataFrame
# YOUR CODE HERE
applicant_data_df = applicant_data_df.drop(['EIN','NAME'],axis=1)

# Review the DataFrame
# YOUR CODE HERE
applicant_data_df

,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL
0,T10,Independent,C1000,ProductDev,Association,1,0,N,5000,1
1,T3,Independent,C2000,Preservation,Co-operative,1,1-9999,N,108590,1
2,T5,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
3,T3,CompanySponsored,C2000,Preservation,Trust,1,10000-24999,N,6692,1
4,T3,Independent,C1000,Heathcare,Trust,1,100000-499999,N,142590,1
...,...,...,...,...,...,...,...,...,...,...
34294,T4,Independent,C1000,ProductDev,Association,1,0,N,5000,0
34295,T4,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
34296,T3,CompanySponsored,C2000,Preservation,Association,1,0,N,5000,0
34297,T5,Independent,C3000,ProductDev,Association,1,0,N,5000,1
34298,T3,Independent,C1000,Preservation,Co-operative,1,1M-5M,N,36500179,0

### Step 3: Encode the dataset’s categorical variables using `OneHotEncoder`, and then place the encoded variables into a new DataFrame.

In [14]:
# Create a list of categorical variables to be encoded using the OneHotEncoder class from sklearn library.
# YOUR CODE HERE
categorical_variables = OneHotEncoder(categories='auto').fit_transform(applicant_data_df.iloc[:,0:1]).toarray()

# Display the categorical variables list
# YOUR CODE HERE
categorical_variables

array([[1., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [15]:
# Create a OneHotEncoder instance
# YOUR CODE HERE
enc = OneHotEncoder(categories='auto')

In [16]:
# Encode the categorical variables using OneHotEncoder
# YOUR CODE HERE
encoded_data = enc.fit_transform(applicant_data_df.iloc[:,0:1]).toarray() # YOUR CODE HERE

In [17]:
# Create a DataFrame with the encoded variables
# YOUR CODE HERE
encoded_df = pd.DataFrame(encoded_data)
# Review the DataFrame
# YOUR CODE HERE
encoded_df

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16
0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
34294,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
34295,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
34296,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
34297,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
34298,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0

### Step 4: Add the original DataFrame’s numerical variables to the DataFrame containing the encoded variables.

> **Note** To complete this step, you will employ the Pandas `concat()` function that was introduced earlier in this course.

In [18]:
# Add the numerical variables from the original DataFrame to the one-hot encoding DataFrame
# YOUR CODE HERE
encoded_df = pd.concat([encoded_df,applicant_data_df.iloc[:,1:]],axis=1)

# Review the Dataframe
# YOUR CODE HERE
encoded_df

,0,1,2,3,4,5,6,7,8,9,...,16,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL
0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,Independent,C1000,ProductDev,Association,1,0,N,5000,1
1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,Independent,C2000,Preservation,Co-operative,1,1-9999,N,108590,1
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,CompanySponsored,C2000,Preservation,Trust,1,10000-24999,N,6692,1
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,Independent,C1000,Heathcare,Trust,1,100000-499999,N,142590,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
34294,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,Independent,C1000,ProductDev,Association,1,0,N,5000,0
34295,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
34296,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,CompanySponsored,C2000,Preservation,Association,1,0,N,5000,0
34297,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,Independent,C3000,ProductDev,Association,1,0,N,5000,1
34298,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,Independent,C1000,Preservation,Co-operative,1,1M-5M,N,36500179,0

### Step 5: Using the preprocessed data, create the features (`X`) and target (`y`) datasets. The target dataset should be defined by the preprocessed DataFrame column “IS_SUCCESSFUL”. The remaining columns should define the features dataset.

In [19]:
# Define the target set y using the IS_SUCCESSFUL column
# YOUR CODE HERE
y = applicant_data_df.iloc[:,1]

# Display a sample of y
# YOUR CODE HERE
y.sample(5)

6619     CompanySponsored
5245          Independent
27884    CompanySponsored
31582    CompanySponsored
33891    CompanySponsored
Name: AFFILIATION, dtype: object

In [20]:
# Define features set X by selecting all columns but IS_SUCCESSFUL
# YOUR CODE HERE
X = encoded_df.iloc[:,1:]

# Review the features DataFrame
# YOUR CODE HERE
X

,1,2,3,4,5,6,7,8,9,10,...,16,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL
0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,Independent,C1000,ProductDev,Association,1,0,N,5000,1
1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,...,0.0,Independent,C2000,Preservation,Co-operative,1,1-9999,N,108590,1
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,...,0.0,CompanySponsored,C2000,Preservation,Trust,1,10000-24999,N,6692,1
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,...,0.0,Independent,C1000,Heathcare,Trust,1,100000-499999,N,142590,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
34294,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,Independent,C1000,ProductDev,Association,1,0,N,5000,0
34295,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
34296,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,...,0.0,CompanySponsored,C2000,Preservation,Association,1,0,N,5000,0
34297,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,Independent,C3000,ProductDev,Association,1,0,N,5000,1
34298,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,...,0.0,Independent,C1000,Preservation,Co-operative,1,1M-5M,N,36500179,0

### Step 6: Split the features and target sets into training and testing datasets.

In [21]:
# Split the preprocessed data into a training and testing dataset
# Assign the function a random_state equal to 1
# YOUR CODE HERE
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=1)

### Step 7: Use scikit-learn's `StandardScaler` to scale the features data.

In [25]:
# Create a StandardScaler instance
# YOUR CODE HERE
scaler = StandardScaler(
    copy=True,
    with_mean=True,
    with_std=True
)# YOUR CODE HERE


# Fit the StandardScaler instance to the training dataset
# YOUR CODE HERE
scaler.fit(X_train) 
# YOUR CODE HERE

# YOUR CODE HERE
X_scaler = scaler.transform(X_train)# YOUR CODE HERE
X_test_scaler = scaler.transform(X_test)# YOUR CODE HERE

# Fit the scaler to the features training dataset
# YOUR CODE HERE
X_train_scaled = scaler.fit_transform(X_train)


# Fit the scaler to the features testing dataset
# YOUR CODE HERE
X_test_scaled = scaler.fit_transform(X_test)

ValueError: could not convert string to float: 'Independent'

---

## Compile and Evaluate a Binary Classification Model Using a Neural Network

### Step 1: Create a deep neural network by assigning the number of input features, the number of layers, and the number of neurons on each layer using Tensorflow’s Keras.

> **Hint** You can start with a two-layer deep neural network model that uses the `relu` activation function for both layers.

In [29]:
# Define the the number of inputs (features) to the model
# YOUR CODE HERE

number_input_features = X_train_scaled.shape[1]


# Review the number of features
number_input_features

NameError: name 'X_train_scaled' is not defined

In [30]:
# Define the number of neurons in the output layer
number_output_neurons = 1

In [31]:
# Define the number of hidden nodes for the first hidden layer

hidden_nodes_layer1 = 10# YOUR CODE HERE

# Review the number hidden nodes in the first layer
hidden_nodes_layer1

10

In [32]:
# Define the number of hidden nodes for the second hidden layer
hidden_nodes_layer2 = 10# YOUR CODE HERE
# YOUR CODE HERE

# Review the number hidden nodes in the second layer
hidden_nodes_layer2

10

In [33]:
# Create the Sequential model instance
# YOUR CODE HERE
nn = Sequential()

In [35]:
# Add the first hidden layer
# YOUR CODE HERE
nn.add(Dense(hidden_nodes_layer1,input_shape=(number_output_neurons,),activation='relu'))
# YOUR CODE HERE

In [36]:
# Add the second hidden layer
# YOUR CODE HERE
nn.add(Dense(hidden_nodes_layer2,activation='relu'))

In [37]:
# Add the output layer to the model specifying the number of output neurons and activation function
# YOUR CODE HERE
nn.add(Dense(number_output_neurons,activation='sigmoid'))

In [38]:
# Display the Sequential model summary
# YOUR CODE HERE
nn.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense (Dense)               (None, 10)                20

 dense_1 (Dense)             (None, 10)                110

 dense_2 (Dense)             (None, 1)                 11

=================================================================
Total params: 141
Trainable params: 141
Non-trainable params: 0
_________________________________________________________________

### Step 2: Compile and fit the model using the `binary_crossentropy` loss function, the `adam` optimizer, and the `accuracy` evaluation metric.

In [39]:
# Compile the Sequential model
# YOUR CODE HERE
nn.compile(optimizer='adam',loss='binary_crossentropy',metrics=['accuracy'])

In [41]:
# Fit the model using 50 epochs and the training data
X_test_scaled = scaler.fit_transform(X_test)
# YOUR CODE HERE

nn.fit(X_train_scaled,y_train,epochs=50)

ValueError: could not convert string to float: 'Independent'

### Step 3: Evaluate the model using the test data to determine the model’s loss and accuracy.

In [42]:
# Evaluate the model loss and accuracy metrics using the evaluate method and the test data
# YOUR CODE HERE
model_loss, model_accuracy = nn.evaluate(X_test_scaled,y_test)

# Display the model loss and accuracy results
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

NameError: name 'X_test_scaled' is not defined

### Step 4: Save and export your model to an HDF5 file, and name the file `AlphabetSoup.h5`.

In [43]:
# Set the model's file path

file_path = Path('./Resources/model.h5')

# Export your model to a HDF5 file
# YOUR CODE HERE
nn.save(file_path)

---

## Optimize the neural network model

### Step 1: Define at least three new deep neural network models (resulting in the original plus 3 optimization attempts). With each, try to improve on your first model’s predictive accuracy.

> **Rewind** Recall that perfect accuracy has a value of 1, so accuracy improves as its value moves closer to 1. To optimize your model for a predictive accuracy as close to 1 as possible, you can use any or all of the following techniques:
>
> * Adjust the input data by dropping different features columns to ensure that no variables or outliers confuse the model.
>
> * Add more neurons (nodes) to a hidden layer.
>
> * Add more hidden layers.
>
> * Use different activation functions for the hidden layers.
>
> * Add to or reduce the number of epochs in the training regimen.

### Alternative Model 1

In [44]:
# Define the the number of inputs (features) to the model
number_input_features = len(X_train.iloc[0])

# Review the number of features
number_input_features

25

In [45]:
# Define the number of neurons in the output layer
number_output_neurons_A1 = 1 # YOUR CODE HERE

In [46]:
# Define the number of hidden nodes for the first hidden layer

hidden_nodes_layer1_A1 = 10 # YOUR CODE HERE

# Review the number of hidden nodes in the first layer
hidden_nodes_layer1_A1

10

In [47]:
# Create the Sequential model instance
nn_A1 = Sequential()

In [48]:
# First hidden layer
# YOUR CODE HERE
nn_A1.add(Dense(hidden_nodes_layer1_A1,input_shape=(number_input_features,),activation='relu'))



# Output layer
# YOUR CODE HERE
nn_A1.add(Dense(number_output_neurons_A1,activation='sigmoid'))


# Check the structure of the model
# YOUR CODE HERE
nn_A1.summary()

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense_3 (Dense)             (None, 10)                260

 dense_4 (Dense)             (None, 1)                 11

=================================================================
Total params: 271
Trainable params: 271
Non-trainable params: 0
_________________________________________________________________

In [49]:
# Compile the Sequential model
nn_A1. compile(optimizer='adam',loss='binary_crossentropy',metrics=['accuracy'])

In [51]:
# Fit the model using 50 epochs and the training data
# YOUR CODE HERE


fit_model_A1 = nn_A1.fit(X_train,y_train,epochs=50)

ValueError: Failed to convert a NumPy array to a Tensor (Unsupported object type float).

#### Alternative Model 2

In [52]:
# Define the the number of inputs (features) to the model
number_input_features = len(X_train.iloc[0])

# Review the number of features
number_input_features

25

In [54]:
# Define the number of neurons in the output layer
number_output_neurons_A2 = 1

In [53]:
# Define the number of hidden nodes for the first hidden layer

hidden_nodes_layer1_A2 = 10

# Review the number of hidden nodes in the first layer
hidden_nodes_layer1_A2

10

In [ ]:
# Create the Sequential model instance
nn_A2 = Sequential()

In [55]:
# First hidden layer
# YOUR CODE HERE
nn_A2.add(Dense(hidden_nodes_layer1_A2,input_shape=(number_input_features,),activation='relu'))

# Output layer
# YOUR CODE HERE
nn_A2.add(Dense(number_output_neurons_A2,activation='sigmoid'))

# Check the structure of the model
# YOUR CODE HERE
nn_A2.summary()

NameError: name 'nn_A2' is not defined

In [ ]:
# Compile the model
# YOUR CODE HERE
nn_A2.compile(optimizer='adam',loss='binary_crossentropy',metrics=['accuracy'])

In [ ]:
# Fit the model
# YOUR CODE HERE
fit_model_A2 = nn_A2.fit(X_train,y_train,epochs=50)

### Step 2: After finishing your models, display the accuracy scores achieved by each model, and compare the results.

In [56]:
print("Original Model Results")

# Evaluate the model loss and accuracy metrics using the evaluate method and the test data
model_loss, model_accuracy = nn.evaluate(X_test_scaled,y_test)

# Display the model loss and accuracy results
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

Original Model Results

NameError: name 'X_test_scaled' is not defined

In [57]:
print("Alternative Model 1 Results")

# Evaluate the model loss and accuracy metrics using the evaluate method and the test data
model_loss, model_accuracy = nn_A1.evaluate(X_test_scaled,y_test)

# Display the model loss and accuracy results
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

Alternative Model 1 Results

NameError: name 'X_test_scaled' is not defined

In [58]:
print("Alternative Model 2 Results")

# Evaluate the model loss and accuracy metrics using the evaluate method and the test data
model_loss, model_accuracy = nn_A2.evaluate(X_test_scaled,y_test)

# Display the model loss and accuracy results
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

Alternative Model 2 Results

NameError: name 'nn_A2' is not defined

### Step 3: Save each of your alternative models as an HDF5 file.

In [59]:
# Set the file path for the first alternative model
file_path = Path('./Resources/model_A1.h5')

# Export your model to a HDF5 file
# YOUR CODE HERE
nn_A1.save(file_path)

In [63]:
# Set the file path for the second alternative model
file_path = Path('./Resources/model_A2.h5') 

# Export your model to a HDF5 file
# YOUR CODE HERE
nn_A2.save(file_path)

NameError: name 'nn_A2' is not defined